version: '2.1.{build}'
image: Visual Studio 2017

clone_depth: 1

build_script:
    - cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
    - cmd: dotnet pack -c Release -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
    - cmd: dotnet test -p:PackageVersion=%APPVEYOR_BUILD_VERSION% test/NUnit.Xml.TestLogger.UnitTests/NUnit.Xml.TestLogger.UnitTests.csproj
    - cmd: dotnet test -p:PackageVersion=%APPVEYOR_BUILD_VERSION% test/NUnit.Xml.TestLogger.AcceptanceTests/NUnit.Xml.TestLogger.AcceptanceTests.csproj

test: off

artifacts:
    - path: 'src\package\bin\Release\*.nupkg'

deploy:
    provider: NuGet
    server: https://www.myget.org/F/spekt/api/v2
    api_key:
        secure: 2C7HbSlU1kcOJ3nzZCpKR97cfWAg/8t38XDf8ywCbJI1ymt93ulfPqT67ugWuMla
    artifact: /.*\.nupkg/
    skip_symbols: true
